name: flask_dev
channels:
  - conda-forge
  - defaults
dependencies:
  #- uwsgi  # unable to install in windows
  - python==3.7.*
  - flask>=1.1
  - flask-sqlalchemy
  - sqlalchemy>=1.3
  - pymysql
  - psycopg2
  - pip:
    - sqlalchemy-views>=0.2
